services:
  postgres:
    image: postgres:16
    container_name: datalab_container
    environment:
      POSTGRES_USER: datalab_user
      POSTGRES_PASSWORD: datalab_pass
      POSTGRES_DB: datalab_db
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
